### ISSUE TITLE
Prevent mailman from moving incoming mail to trash

### ISSUE THREAD

**Issue by mbajur** [titanous/mailman#112]
Hello!
I'm using the following code to receive my mails:

    require "rubygems"
    require "bundler/setup"
    require "mailman"
    #Mailman.config.logger = Logger.new("log/mailman.log")  # uncomment this if you can want to create a log file
    Mailman.config.poll_interval = 3  # change this number as per your needs. Default is 60 seconds
    Mailman.config.pop3 = {
      server: 'x.x.x', port: 995, ssl: true,
      username: "x",
      password: "y"
    }
      Mailman::Application.run do
      default do
        begin
        p "Found a new message"
        p message.from.first # message.from is an array
        p message.to.first # message.to is an array again..
        p message.subject
        rescue Exception => e
          Mailman.logger.error "Exception occurred while receiving message:n#{message}"
          Mailman.logger.error [e, *e.backtrace].join("n")
        end
      end
    end

And basically everything works as it should - BUT! All my mails are beeing moved to trash folder of my mailbox. Is there any way to disable that behaviour? It might sound silly that i need such option but i really do.

Thanks in advance.

**Comment by titanous** [comment]
Use IMAP, which will mark the messages as read. The only other option with POP3 is to keep a local database of messages that have been seen, but Mailman does not currently support this.

**Comment by mbajur** [comment]
Oh, so that's a POP3 thing. Great! Thanks for your super fast reply :)
Just one more thing is bothering me - are we able to interact with specific messages? I need to somehow read all the new messages without changing their state to "read". I suppose it's a default behaviour to change the message state after reading it so maybe there is any way change the state after read process?

**Comment by titanous** [comment]
You're better off implementing your own custom IMAP client to do that. Mailman is specifically about building email processing where it "owns" the inbox. The code is permissively licensed, so feel free to copy/paste as much code as you want as long as you follow the terms!

**Comment by mbajur** [comment]
Ok, thanks for your help!
